apiVersion: apps/v1
kind: Deployment
metadata:
  name: doplarr-deployment
  labels:
    app: doplarr
  namespace: doplarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: doplarr
  template:
    metadata:
      labels:
        app: doplarr
    spec:
      nodeName: pikachu
      containers:
        - name: doplarr
          image: lscr.io/linuxserver/doplarr:latest
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/Chicago
            - name: DISCORD__TOKEN
              value: "MTE4NTM0NjgxMTY3MDU2NDkzNA.GdGOHD.x2l44p1mslSotSzwUYtp00sMaYgTo_xYb0d-Go"
            - name: RADARR__API
              value: "b87a2d0f93654958ad5e0301eb3085a1"
            - name: RADARR__URL
              value: "https://radarr.eaglepass.io"
            - name: SONARR__API
              value: "f97d946bdb574d338babef75056725b7"
            - name: SONARR__URL
              value: "https://sonarr.eaglepass.io"
            - name: DISCORD__MAS_RESULTS
              value: "25"
            - name: DISCORD__REQUESTED_MSG_STYLE
              value: ":embed"
            - name: RADARR__QUALITY_PROFILE
              value: "Any"
            - name: RADARR__LANGUAGE_PROFILE
              value: "English"
            - name: SONARR__QUALITY_PROFILE
              value: "Any"
            - name: SONARR__LANGUAGE_PROFILE
              value: "English"
            - name: PARTIAL_SEASONS
              value: "true"
            - name: LOG_LEVEL
              value: ":error"
      volumes:
        - name: config
          nfs:
            server: 10.0.50.3
            path: /mnt/user/doplarr_config