apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: requestrr-ingress
  labels:
    app: requestrr
    app.kubernetes.io/name: requestrr
    app.kubernetes.io/instance: requestrr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Requestrr
    hajimari.io/icon: surround-sound
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - requestrr.eaglepass.io
      secretName: requestrr-tls-certificate
  rules:
    - host: requestrr.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: requestrr-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: requestrr-service
  labels:
    app: requestrr
    app.kubernetes.io/name: requestrr
    app.kubernetes.io/instance: requestrr
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 4545
      targetPort: http
      protocol: TCP
  selector:
    app: requestrr

---
apiVersion: v1
kind: Service
metadata:
  name: requestrr-downloader
  labels:
    app: requestrr
    app.kubernetes.io/name: requestrr
    app.kubernetes.io/instance: requestrr
spec:
  clusterIP: 10.43.10.25
  ports:
    - name: http
      port: 4545
      targetPort: 4545
      protocol: TCP
  selector:
    app: requestrr
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr-deployment
  labels:
    app: requestrr
  namespace: requestrr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: requestrr
  template:
    metadata:
      labels:
        app: requestrr
    spec:
      containers:
        - name: requestrr
          image: darkalfx/requestrr:latest
          volumeMounts:
            - name: config
              mountPath: /root/config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 4545
      volumes:
        - name: config
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.requestrr
            lun: 0
            fsType: ext4
            readOnly: false
