plex:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Plex
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host plex.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host

  service:
    main:
      primary: true
      ports:
        http:
          port: 32400
    dnla-tcp:
      enabled: false
      type: NodePort
      ports:
        dnla-tcp:
          enabled: true
          port: 32469
          protocol: TCP
          targetPort: 32469
      externalTrafficPolicy: Local
    dnla-udp:
      enabled: false
      type: NodePort
      ports:
        dnla-udp:
          enabled: true
          port: 1900
          protocol: TCP
          targetPort: 1900
      externalTrafficPolicy: Local

  image:
    repository: lscr.io/linuxserver/plex
    tag: latest
    pullPolicy: IfNotPresent
  
  env:
    TZ: America/Chicago
    PGID: 100
    PUID: 99
    VERSION: docker
  
  # podSecurityContext:
  #   runAsUser: 99
  #   runAsGroup: 100

  
  # nodeSelector:
  nodeName: pikachu
  
  volumeMounts: []
    - name: config
      mountPath: /config
    - name: transcode
      mountPath: /transcode
    - name: dev-dri
      mountPath: /dev/dri
    - name: movies
      mountPath: /movies
    - name: tv
      mountPath: /tv
    - name: backup
      mountPath: /backups

  volumes: []
    - name: config
      hostPath:
        path: /plex/config
    - name: backup
      nfs:
        server: 10.0.50.3
        path: /mnt/user/plex_backups
    - name: transcode
      hostPath:
        path: /plex/transcode
    - name: dev-dri
      hostPath:
        path: /dev/dri
    - name: movies
      nfs:
        server: 10.0.50.3
        path: /mnt/user/movies
    - name: tv
      nfs:
        server: 10.0.50.3
        path: /mnt/user/tv