plex:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Plex
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host plex.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host
