connect:
  ports:
  - name: http
    port: 32400
    protocol: TCP
    targetPort: http
  - name: http4
    port: 32469
    protocol: TCP
    targetPort: 32469
  - name: http5
    port: 1900
    protocol: UDP
    targetPort: 1900
  type: ClusterIP
deployment:
  plex:
    env:
      pgid: "100"
      puid: "99"
      tz: America/Chicago
      version: docker
    image:
      repository: lscr.io/linuxserver/plex
      tag: latest
  replicas: 1
kubernetesClusterDomain: cluster.local
