apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  labels:
    app: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hajimari.io/appName: Jellyfin
    hajimari.io/icon: movie-roll
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyfin.eaglepass.io
      secretName: jellyfin-tls-certificate
  rules:
    - host: jellyfin.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: jellyfin-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  labels:
    app: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 8096
      targetPort: http
      protocol: TCP
  selector:
    app: jellyfin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: dev-dri
              mountPath: /dev/dri
            - name: movies
              mountPath: /data/movies
            - name: movies2
              mountPath: /data/movies2
            - name: tv
              mountPath: /data/tv
            - name: tv2
              mountPath: /data/tv2
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: America/Chicago
            - name: JELLYFIN_PublishedServerUrl
              value: "192.168.1.27"
          ports:
            - name: http
              containerPort: 8096
      volumes:
        - name: config
          iscsi:
            targetPortal: 192.168.1.2:3260
            portals: ["192.168.1.2:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.jellyfinconfig
            lun: 0
            fsType: ext4
            readOnly: false
        - name: transcode
          iscsi:
            targetPortal: 192.168.1.2:3260
            portals: ["192.168.1.2:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.jellyfintranscode
            lun: 0
            fsType: ext4
            readOnly: false
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: movies
          nfs:
            server: 10.0.50.1
            path: /volume3/Madripoor/movies
        - name: movies2
          nfs:
            server: 10.0.50.1
            path: /volume25/Asgard/movies
        - name: tv
          nfs:
            server: 10.0.50.1
            path: /volume3/Wakanda/tv
        - name: tv2
          nfs:
            server: 10.0.50.1
            path: /volume25/Neverland/tv