jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host jellyfin.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host
  
  volumeMounts:
    movies:
      mountPath: /data/movies

  volumes:
    movies:
      enabled: true
      type: nfs
      nfs:
        server: 10.0.50.3
        path: /mnt/user/movies