apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emby
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: emby
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: media
      interval: 1h
  values:
    image:
      repository: lscr.io/linuxserver/emby
      tag: latest
    service:
      main:
        ports:
          http:
            ports:
              - port: 8096
              - port: 8920
  volumeMounts:
    - name: config
      mountPath: /config
    - name: transcode
      mountPath: /transcode
    - name: dev-dri
      mountPath: /dev/dri
    - name: movies
      mountPath: /data/movies
    - name: movies2
      mountPath: /data/movies2
    - name: tv
      mountPath: /data/tv
    - name: tv2
      mountPath: /data/tv2
    - name: backup
      mountPath: /external_backup
  persistence:
    volumeMounts:
      - name: config
        mountPath: /config
      - name: transcode
        mountPath: /transcode
      - name: dev-dri
        mountPath: /dev/dri
      - name: movies
        mountPath: /data/movies
      - name: movies2
        mountPath: /data/movies2
      - name: tv
        mountPath: /data/tv
      - name: tv2
        mountPath: /data/tv2
      - name: backup
        mountPath: /external_backup
  ingress:
    main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Emby
      hajimari.io/icon: filmstrip
    hosts:
      - host: &host emby.eaglepass.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: emby-tls-certificate
        hosts:
          - *host
  extraEnvs:
    - name: PUID
      value: "0"
    - name: PGID
      value: "0"
    - name: TZ
      value: America/Chicago
  volumes:
    - name: config
      iscsi:
        targetPortal: 10.0.50.1:3260
        portals: ["10.0.50.1:3260"]
        iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.embyconfig
        lun: 0
        fsType: ext4
        readOnly: false
    - name: backup
      nfs:
        server: 10.0.50.1
        path: /volume2/emby-config-backup
    - name: transcode
      iscsi:
        targetPortal: 10.0.50.1:3260
        portals: ["10.0.50.1:3260"]
        iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.embytranscode
        lun: 0
        fsType: ext4
        readOnly: false
    - name: dev-dri
      hostPath:
        path: /dev/dri
    - name: movies
      nfs:
        server: 10.0.50.1
        path: /volume3/Madripoor/movies
    - name: movies2
      nfs:
        server: 10.0.50.1
        path: /volume26/Asgard/movies
    - name: tv
      nfs:
        server: 10.0.50.1
        path: /volume3/Wakanda/tv
    - name: tv2
      nfs:
        server: 10.0.50.1
        path: /volume26/Neverland/tv
  resources:
    requests:
      cpu: 2
      memory: 8G
    limits:
      memory: 12G