apiVersion: v1
kind: Namespace
metadata:
  name: emby
  labels:
    app: emby

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emby-ingress
  labels:
    app: emby
  namespace: emby
spec:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Emby
    hajimari.io/icon: movie-cog
    # kubernetes.io/tls-acme: "true"
  hosts:
    - emby.eaglepass.io
  tls:
    - secretName: emby-tls-certificate
      hosts:
        - emby.eaglepass.io
  ports:
    - name: emby
      port: 8096
      targetPort: 8096
      protocol: TCP
    - name: emby-comp
      port: 8920
      targetPort: 8920
      protocol: TCP
  selector:
    app: emby

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
  namespace: emby
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
        - name: emby
          image: lscr.io/linuxserver/emby
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: dev-dri
              mountPath: /dev/dri
            - name: movies
              mountPath: /data/movies
            - name: movies2
              mountPath: /data/movies2
            - name: tv
              mountPath: /data/tv
            - name: tv2
              mountPath: /data/tv2
            - name: backup
              mountPath: /external_backup
          resources:
            limits:
              cpu: "12"
              memory: "30Gi"
            requests:
              cpu: "8"
              memory: "15Gi"
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: America/Chicago
          ports:
            - name: emby
              containerPort: 8096
            - name: emby-comp
              containerPort: 8920
      volumes:
        - name: config
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.embyconfig
            lun: 0
            fsType: ext4
            readOnly: false
        - name: backup
          nfs:
            server: 10.0.50.1
            path: /volume2/emby-config-backup
        - name: transcode
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.embytranscode
            lun: 0
            fsType: ext4
            readOnly: false
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: movies
          nfs:
            server: 10.0.50.1
            path: /volume3/Madripoor/movies
        - name: movies2
          nfs:
            server: 10.0.50.1
            path: /volume26/Asgard/movies
        - name: tv
          nfs:
            server: 10.0.50.1
            path: /volume3/Wakanda/tv
        - name: tv2
          nfs:
            server: 10.0.50.1
            path: /volume26/Neverland/tv
