apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  labels:
    app: plex
  namespace: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - env:
        - name: PUID
          value: {{ quote .Values.deployment.plex.env.puid }}
        - name: PGID
          value: {{ quote .Values.deployment.plex.env.pgid }}
        - name: VERSION
          value: {{ quote .Values.deployment.plex.env.version }}
        - name: TZ
          value: {{ quote .Values.deployment.plex.env.tz }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.plex.image.repository }}:{{ .Values.deployment.plex.image.tag }}
        name: plex
      volumes:
        - name: config
          hostPath:
            path: /plex/config
        - name: backup
          nfs:
            server: 10.0.50.3
            path: /mnt/user/plex_backups
        - name: transcode
          hostPath:
            path: /plex/transcode
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: movies
          nfs:
            server: 10.0.50.3
            path: /mnt/user/movies
        - name: tv
          nfs:
            server: 10.0.50.3
            path: /mnt/user/tv