- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade
    - role: cronjobs
      tags: cronjobs

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - metallb_config
