- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade

- name: Setup NFS
  hosts: metal
  roles:
    - nfs_utils

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - metallb_config
