- name: Create Kubernetes cluster and Setup NFS
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade
    - nfs_utils

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - metallb_config
