- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - prerequisites
    - k3s
    - automatic_upgrade
    - nfs_utils
    - cronjobs

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium
