apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headphones-ingress
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Headphones
    hajimari.io/icon: surround-sound
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - headphones.eaglepass.io
      secretName: headphones-tls-certificate
  rules:
    - host: headphones.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: headphones-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: headphones-service
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 8181
      targetPort: http
      protocol: TCP
  selector:
    app: headphones

---
apiVersion: v1
kind: Service
metadata:
  name: headphones-connect
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
spec:
  clusterIP: 10.43.10.217
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
  selector:
    app: headphones
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headphones-deployment
  labels:
    app: headphones
  namespace: headphones
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: headphones
  template:
    metadata:
      labels:
        app: headphones
    spec:
      nodeName: pikachu
      containers:
        - name: headphones
          image: lscr.io/linuxserver/headphones:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: backup-config
              mountPath: /backups
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /music
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: LANGUAGE
              value: en_US.UTF-8
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 8181
      volumes:
        - name: backup-config
          nfs:
            server: 10.0.50.3
            path: /mnt/user/headphones_backups
        - name: config
          hostPath:
            path: /headphones/config
        - name: downloads
          nfs:
            server: 10.0.50.3
            path: /mnt/user/downloads
        - name: music
          nfs:
            server: 10.0.50.3
            path: /mnt/user/musicapiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headphones-ingress
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Headphones
    hajimari.io/icon: surround-sound
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - headphones.eaglepass.io
      secretName: headphones-tls-certificate
  rules:
    - host: headphones.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: headphones-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: headphones-service
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 8181
      targetPort: http
      protocol: TCP
  selector:
    app: headphones

---
apiVersion: v1
kind: Service
metadata:
  name: headphones-connect
  labels:
    app: headphones
    app.kubernetes.io/name: headphones
    app.kubernetes.io/instance: headphones
spec:
  clusterIP: 10.43.10.217
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
  selector:
    app: headphones
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headphones-deployment
  labels:
    app: headphones
  namespace: headphones
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: headphones
  template:
    metadata:
      labels:
        app: headphones
    spec:
      nodeName: pikachu
      containers:
        - name: headphones
          image: lscr.io/linuxserver/headphones:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: backup-config
              mountPath: /backups
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /music
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: LANGUAGE
              value: en_US.UTF-8
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 8181
      volumes:
        - name: backup-config
          nfs:
            server: 10.0.50.3
            path: /mnt/user/headphones_backups
        - name: config
          hostPath:
            path: /headphones/config
        - name: downloads
          nfs:
            server: 10.0.50.3
            path: /mnt/user/downloads
        - name: music
          nfs:
            server: 10.0.50.3
            path: /mnt/user/music