apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ansible-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: /metal/ssh
        property: private_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        credentials.tfrc.json: |
          {
            "credentials": {
              "app.terraform.io": {
                "token": "LM4tH6cF8TkTvg.atlasv1.iEjXkxoHYi0m8hsZyOAfpMkSjMKyGCiGrE4P7WxF4VyT2OjlwvDYG3zgpu856sE4cRE"
              }
            }
          }
        terraform.tfvars: |
          cloudflare_email = "chrisnelsonx@gmail.com"
          cloudflare_api_key = "599550098b522fc511ee93348525ea38c5431"
          cloudflare_account_id = "33780c6eabd9daae5bc57ef508339da4"
  data:
    - secretKey: terraform_cloud_token
      remoteRef:
        key: /external/terraform-cloud
        property: token
    - secretKey: cloudflare_email
      remoteRef:
        key: /external/cloudflare
        property: email
    - secretKey: cloudflare_api_key
      remoteRef:
        key: /external/cloudflare
        property: api_key
    - secretKey: cloudflare_account_id
      remoteRef:
        key: /external/cloudflare
        property: account_id
