apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
  labels:
    app: bazarr
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Bazarr
    hajimari.io/icon: subtitles
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bazarr.eaglepass.io
      secretName: bazarr-tls-certificate
  rules:
    - host: bazarr.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: bazarr-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
  labels:
    app: bazarr
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 8989
      targetPort: http
      protocol: TCP
  selector:
    app: bazarr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr-deployment
  labels:
    app: bazarr
  namespace: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: movies
              mountPath: /movies
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 6767

      volumes:
        - name: config
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.bazarr
            lun: 0
            fsType: ext4
            readOnly: false
        - name: tv
          nfs:
            server: 10.0.50.1
            path: /volume3/Wakanda/tv
        - name: movies
          nfs:
            server: 10.0.50.1
            path: /volume3/Madripoor/movies