- name: Install packages for automatic upgrade and Setup NFS
  ansible.builtin.dnf:
    name:
      - dnf-automatic
      - dnf-utils
      - nfs-utils

- name: Copy automatic upgrade config file
  ansible.builtin.copy:
    src: automatic.conf
    dest: /etc/dnf/automatic.conf
    mode: 0644

- name: Enable automatic upgrade service
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
