apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget-ingress
  labels:
    app: nzbget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: NZBGet
    hajimari.io/icon: download-network-outline
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nzbget.eaglepass.io
      secretName: nzbget-tls-certificate
  rules:
    - host: nzbget.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: nzbget
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: nzbget-service
  labels:
    app: nzbget
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: http
      targetPort: 6789
      protocol: TCP
  selector:
    app: nzbget

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  labels:
    app: nzbget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: downloads
              mountPath: /downloads
            - name: intermediate
              mountPath: /intermediate
            - name: apps
              mountPath: /apps
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 6789
      volumes:
        - name: config
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.nzbgetconfig
            lun: 0
            fsType: ext4
            readOnly: false
        - name: data
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.nzbgetdata
            lun: 0
            fsType: ext4
            readOnly: false
        - name: intermediate
          iscsi:
            targetPortal: 10.0.50.1:3260
            portals: ["10.0.50.1:3260"]
            iqn: iqn.2011-08.com.asustor:as5304t-8ddc73.nzbgetinter
            lun: 0
            fsType: ext4
            readOnly: false
        - name: downloads
          nfs:
            server: 10.0.50.1
            path: /volume2/downloads
        - name: apps
          nfs:
            server: 10.0.50.1
            path: /volume3/Tatooine/apps
