name: Build and Deploy MkDocs
on:
  push:
    paths:
      - 'docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install MkDocs
        run: pip install mkdocs
      
      - name: Install dependencies
        run: pip install mkdocs-material pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: actions/github-script@v7
        with:
          script: |
            github.actions.createBranch(ref, { force: true });
            github.actions.checkout(ref);
            github.actions.uploadArtifact('public', '**');